# Generated by Django 4.2.1 on 2024-08-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre', '0002_piece_description_piece_language_piece_pages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
